### ISSUE TITLE
Request for Crossreferenced GHC 8.2.1

### ISSUE THREAD

**Issue by nh2** [google/haskell-indexer#56]
Hi @robinp,

you [recently made a crossreferenced GHC 8.0.1](https://mail.haskell.org/pipermail/ghc-devs/2017-June/014338.html).

Could you make one for 8.2.1 as well (and maybe host them both under qualified URLs, and have http://stuff.codereview.me/#ghc show to the latest one)?

That would be very useful.

Thanks!

(Also I linked your post [on Reddit](https://www.reddit.com/r/haskell/comments/6p4v50/ghc_crossreferenced_with_haskellindexer/) so that not-ghc-devs-subscribers know about it as well!)

**Comment by robinp** [comment]
Thanks for the request Niklas! Due to vacation I'm out of reach of usual resources for a bit, however:

- Note that 8.2.1-rc2 is already indexed if it suits you in the mean time, and is available from a separate Kythe corpus "ghc-8.2.1-rc2" (click it on the left). See http://stuff.codereview.me/#ghc/compiler/main/GHC.hs?corpus=ghc-8.2.1-rc2&signature. Unfortunately I indexed 8.0.2 with the empty corpus (for that click the "::" in top-left).

- Note that the way I indexed was very basic - transformed the output of the `make` command, and ran `ghc-kythe-wrapper` over it. See `index-ghc.sh` in https://gist.github.com/robinp/222cf3a39cc19178ec8691522056d7fe. I suspect some code like GHCi or tests are missing from the coverage. Would you be interested in making a more complete script?

- Disclaimer: the index&server is just stashed on a low-power instance, and has poor latency. For the time it's rather meant as a proof of concept than a reliable source.

**Comment by nh2** [comment]
> Note that 8.2.1-rc2 is already indexed if it suits you in the mean time

OK awesome, that's already good enough for me for now. I wish you a nice vacation!

> Would you be interested in making a more complete script?

In general yes but right now what it already has seems sufficient for me to find the call sites I care about.

> the index&server is just stashed on a low-power instance, and has poor latency

Would it be possible for the server (or otherwise) to offer the files for download, so that I can `./serve` them locally?

**Comment by robinp** [comment]
@nh2: I packed the serving table to https://storage.googleapis.com/index-tables/tbl-v0.tar. Can run kythe on it using `/opt/kythe/tools/http_server --serving_table tbl-v0 --listen 0.0.0.0:8080 --public_resources /opt/kythe/web/ui` after extraction.

**Comment by nh2** [comment]
Thanks, that's working!
